name: 'Create ruleset' 
description: 'Creates ruleset in repository'
inputs:
  api_version:
    description: 'Version of API to use'
    default: '2022-11-28'
  token:
    required: true
    description: 'GitHub token'
  owner: 
    required: true
    description: 'Owner of repository'
  repository:
    required: true
    description: 'Repository name'
  ruleset_path:
    required: true
    description: 'Path to JSON with ruleset'
  
runs:
  using: composite
  steps:

  - name: 'API call'
    shell: bash
    run: |
      . ${GITHUB_ACTION_PATH}/script.sh \
        --api_version "${{ inputs.api_version }}" \
        --token "${{ inputs.token }}" \
        --owner "${{ inputs.owner }}" \
        --repository "${{ inputs.repository }}" \
        --ruleset_path "${{ inputs.ruleset_path }}"
  