name: restore
description: 'restore dependencies'
runs:
  using: composite
  steps:
  - uses: actions/setup-node@v4
    with:
      node-version: 21
      cache: pnpm
      cache-dependency-path: pnpm-lock.yaml
