name: 'Link repository to project' 
description: 'Links repository to project with GitHub GraphQL API'
inputs:
  repository:
    required: true
    description: 'Repository ID'
  project:
    required: true
    description: 'Project ID'
  token:
    required: true
    description: 'GitHub token'
  
runs:
  using: composite
  steps:

  - name: 'Link API'
    shell: bash
    run: |
      . ${GITHUB_ACTION_PATH}/script.sh \
        --token "${{ inputs.token }}" \
        --repository "${{ inputs.repository }}" \
        --project "${{ inputs.project }}"
