name: 'Link repository to project' 
description: 'Links repository to project with GitHub GraphQL API'
inputs:
  repository:
    required: true
    description: 'Repository ID'
  project:
    required: true
    description: 'Project ID'
  token:
    required: true
    description: 'GitHub token'
  
runs:
  using: node16
  main: ${GITHUB_ACTION_PATH}/dist/index.js
