name: 'Update repository' 
description: 'Updates repository with GitHub REST API'
inputs:
  api_version:
    description: 'API version to use'
    default: '2022-11-28'
  repository:
    required: true
    description: 'The name of the repository without the .git extension. The name is not case sensitive.'
  owner:
    required: true
    description: 'The account owner of the repository. The name is not case sensitive.'
  token:
    required: true
    description: 'GitHub token'

  name:
    description: 'The name of the repository.'
  description:
    description: 'A short description of the repository.'
  delete_branch_on_merge:
    description: |
      Either true to allow automatically deleting head branches 
      when pull requests are merged, or false to prevent automatic deletion.
  allow_auto_merge:
    description: |
      Either true to allow auto-merge on pull requests, or false to disallow auto-merge.
  
runs:
  using: composite
  steps:

  - name: 'API Call'
    shell: bash
    run: |
      . ${GITHUB_ACTION_PATH}/script.sh \
        --api_version "${{ inputs.api_version }}" \
        --token "${{ inputs.token }}" \
        --repository "${{ inputs.repository }}" \
        --owner "${{ inputs.owner }}" \
        --name "${{ inputs.name }}" \
        --description "${{ inputs.description }}" \
        --delete_branch_on_merge "${{ inputs.delete_branch_on_merge }}" \
        --allow_auto_merge "${{ inputs.allow_auto_merge }}"
